version: '3.8'
services:
  authentication-service:
    build:
      context: .
      dockerfile: ./Service.Authentication/Dockerfile
    expose:
      - "5001"
    volumes:
      - /srv/aion/auth-keys:/jwt:rw,z
    environment:
      - TZ=Europe/Berlin
      - ASPNETCORE_ENVIRONMENT=Production
      - CLIENT_ID=internal-service
      - CLIENT_SECRET=388D45FA-B36B-4988-BA59-B187D329C207 #Test only
    restart: unless-stopped
  
  core-service:
    build:
      context: .
      dockerfile: ./Core.Boot/Dockerfile
    expose:
      - "8081"
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=aion;Username=aionuser;Password=aionpass
      - TZ=Europe/Berlin
      - TOKEN_URL=https://authentication-service:5001/connect/token
      - CLIENT_ID=internal-service
      - CLIENT_SECRET=388D45FA-B36B-4988-BA59-B187D329C207 #Test only
    depends_on:
      - postgres
      - authentication-service
    restart: unless-stopped
    volumes:
      - /srv/aion/auth-keys:/jwt:ro,z
      - /var/lib/docker/volumes/npm_npm-ssl/_data/archive/npm-9:/certs:ro,z

  monitoring-service:
    build:
      context: .
      dockerfile: ./Service.Monitoring/Dockerfile
    expose:
      - "8083"
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - TZ=Europe/Berlin
      - TOKEN_URL=https://authentication-service:5001/connect/token
      - CLIENT_ID=internal-service
      - CLIENT_SECRET=388D45FA-B36B-4988-BA59-B187D329C207 #Test only
    volumes:
      - /srv/aion/auth-keys:/jwt:ro,z
      - /var/lib/docker/volumes/npm_npm-ssl/_data/archive/npm-9:/certs:ro,z
    depends_on:
      - core-service
      - authentication-service
    restart: unless-stopped

  admin-web:
    build:
      context: .
      dockerfile: ./Service.Admin.Web/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - TZ=Europe/Berlin
      - TOKEN_URL=https://authentication-service:5001/connect/token
      - CLIENT_ID=internal-service
      - CLIENT_SECRET=388D45FA-B36B-4988-BA59-B187D329C207 #Test only
    volumes:
      - /srv/aion/auth-keys:/jwt:ro,z
    depends_on:
      - monitoring-service
      - core-service
      - authentication-service
    restart: unless-stopped

  postgres:
    image: postgres:16.4
    environment:
      - POSTGRES_DB=aion
      - POSTGRES_USER=aionuser
      - POSTGRES_PASSWORD=aionpass
      - TZ=Europe/Berlin
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aionuser -d aion" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
