version: '3.8'
services:
  authentication-service:
    build:
      context: .
      dockerfile: ./Service.Authentication/Dockerfile
    expose:
      - "5001"
    volumes:
    - ./auth-keys:/certs:ro,z
    - ./DataProtection-Keys:/app/DataProtection-Keys:rw
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
  
  core-service:
    build:
      context: .
      dockerfile: ./Core.Boot/Dockerfile
    expose:
      - "8081"
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=aion;Username=aionuser;Password=aionpass
      - TZ=Europe/Berlin
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/npm_npm-ssl/_data/archive/npm-9:/certs:ro,Z
      - ./DataProtection-Keys:/app/DataProtection-Keys:rw

  monitoring-service:
    build:
      context: .
      dockerfile: ./Service.Monitoring/Dockerfile
    expose:
      - "8083"
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - TZ=Europe/Berlin
    volumes:
      - /var/lib/docker/volumes/npm_npm-ssl/_data/archive/npm-9:/certs:ro,Z
      - ./DataProtection-Keys:/app/DataProtection-Keys:rw
    depends_on:
      - core-service
    restart: unless-stopped

  admin-web:
    build:
      context: .
      dockerfile: ./Service.Admin.Web/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - TZ=Europe/Berlin
    volumes:
      - ./DataProtection-Keys:/app/DataProtection-Keys:rw
    depends_on:
      - monitoring-service
      - core-service
    restart: unless-stopped

  postgres:
    image: postgres:16.4
    environment:
      - POSTGRES_DB=aion
      - POSTGRES_USER=aionuser
      - POSTGRES_PASSWORD=aionpass
      - TZ=Europe/Berlin
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aionuser -d aion" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  data_protection_keys:
