version: '3.8'
services:
  core-service:
    build:
      context: .
      dockerfile: ./Core.Boot/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=aion;Username=aionuser;Password=aionpass
      - TZ=Europe/Berlin
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./Certificates:/app/certs:ro
      - data_protection_keys:/app/DataProtection-Keys:rw

  monitoring-service:
    build:
      context: .
      dockerfile: ./Service.Monitoring/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - TZ=Europe/Berlin
    volumes:
      - ./Certificates:/app/certs:ro
      - data_protection_keys:/app/DataProtection-Keys:rw
    depends_on:
      - core-service
    restart: unless-stopped

  admin-web:
    build:
      context: .
      dockerfile: ./Service.Admin.Web/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - TZ=Europe/Berlin
    volumes:
      - ./Certificates:/app/certs:ro
      - data_protection_keys:/app/DataProtection-Keys:rw
    depends_on:
      - monitoring-service
      - core-service
    restart: unless-stopped

  postgres:
    image: postgres:16.4
    environment:
      - POSTGRES_DB=aion
      - POSTGRES_USER=aionuser
      - POSTGRES_PASSWORD=aionpass
      - TZ=Europe/Berlin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aionuser -d aion" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - TZ=Europe/Berlin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
    restart: unless-stopped

volumes:
  postgres_data:
  data_protection_keys:
